name: Monthly File Change Backup

on:
  push:
    paths:
      - "*.json"  # Отслеживает изменения всех JSON-файлов в корне репозитория

  workflow_dispatch:  # Возможность запустить вручную

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create backup copies
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p backups/$TIMESTAMP
          
          # Найти все файлы YYYY-MM.json и скопировать их в папку бэкапов
          for file in *.json; do
            if [[ $file =~ ^[0-9]{4}-[0-9]{2}\.json$ ]]; then
              cp "$file" "backups/$TIMESTAMP/$file"
            fi
          done

          git add backups/$TIMESTAMP/
          git commit -m "Backup on $TIMESTAMP due to file change" || echo "No changes to commit"
          git push
