name = "tips-api"
main = "worker/index.js"
compatibility_date = "2025-09-30"

[vars]
# API_PASSWORD is set via Wrangler secrets in production:
# wrangler secret put API_PASSWORD

[[d1_databases]]
binding = "DB"
database_name = "tip-data"
database_id = "dfe5ea4f-2a93-4b97-b5e5-8909a6b0a54a"

[observability]
enabled = true

# Optional route (customize for your zone)
# [[routes]]
# pattern = "staff.you.ge/api/d1*"
# zone_id = "<your-zone-id>"

# Changelog:
# 2025-09-31 - Initial wrangler config with D1 binding (GPT-5)
