name: Backup Changed JSON Files test

on:
  push:
    paths:
      - "*.json"  # აკონტროლებს მხოლოდ .json ფაილების ცვლილებებს

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # საჭიროა რეპოზიტორიაში ცვლილებების შესატანად

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # უზრუნველყოფს სრული გიტ ისტორიის მიღებას

      - name: Get list of changed JSON files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            *.json

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Backup changed JSON files
        if: steps.changed-files.outputs.all_changed_files != 'true'
        run: |
          MONTH=$(date +"%Y-%m")  # მაგალითად: 2025-02
          TIMESTAMP=$(date +"%d.%m-%H.%M")  # მაგალითად: 09.02-14.30
          mkdir -p backups/$MONTH  # ვქმნით მიმდინარე თვის საქაღალდეს

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            BASENAME=$(basename "$file")  # ვიღებთ მხოლოდ ფაილის სახელს
            cp "$file" "backups/$MONTH/$TIMESTAMP-$BASENAME"
          done

          git add backups/$MONTH/
          git commit -m "Backup JSON files on $TIMESTAMP"

          # ვათანაბრებთ ლოკალურ და რემოუთ ბრენჩს
          git pull --rebase origin main
          git push

      - name: Ensure backups directory is tracked
        run: |
          touch backups/.gitkeep
          git add backups/.gitkeep || true
          git commit -m "Ensure backups directory exists" || true
          git push || true
