name: Send Push Notification

on:
  workflow_dispatch:  # рЃ«рЃћрЃџрЃўрЃЌ рЃњрЃљрЃерЃЋрЃћрЃЉрЃљ GitHub Actions-рЃўрЃЊрЃљрЃю

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install web-push

      - name: Send Push Notification
        run: |
          node -e '
          const webPush = require("web-push");
          const vapidKeys = {
              publicKey: process.env.VAPID_PUBLIC_KEY,
              privateKey: process.env.VAPID_PRIVATE_KEY
          };
          webPush.setVapidDetails(
              "mailto:your-email@example.com",
              vapidKeys.publicKey,
              vapidKeys.privateKey
          );
          const subscription = JSON.parse(process.env.PUSH_SUBSCRIPTION);
          const payload = JSON.stringify({
              title: "­ЪЊб рЃљрЃ«рЃљрЃџрЃў рЃерЃћрЃбрЃДрЃЮрЃЉрЃўрЃюрЃћрЃЉрЃљ!",
              body: "рЃћрЃА рЃљрЃарЃўрЃА рЃбрЃћрЃАрЃбрЃБрЃарЃў Push рЃерЃћрЃбрЃДрЃЮрЃЉрЃўрЃюрЃћрЃЉрЃљ.",
              icon: "/icon.png"
          });
          webPush.sendNotification(subscription, payload).then(() => {
              console.log("РюЁ рЃерЃћрЃбрЃДрЃЮрЃЉрЃўрЃюрЃћрЃЉрЃљ рЃњрЃљрЃњрЃќрЃљрЃЋрЃюрЃўрЃџрЃўрЃљ!");
          }).catch((err) => {
              console.error("РЮї рЃерЃћрЃфрЃЊрЃЮрЃЏрЃљ Push рЃњрЃљрЃњрЃќрЃљрЃЋрЃюрЃўрЃАрЃљрЃА:", err);
          });
          '
        env:
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
          PUSH_SUBSCRIPTION: ${{ secrets.PUSH_SUBSCRIPTION }}
